# Generated by Django 3.2.15 on 2022-09-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=100)),
                ('contectno', models.IntegerField(max_length=12)),
                ('emailaddress', models.EmailField(max_length=50)),
                ('manno', models.CharField(max_length=10)),
                ('aadharno', models.CharField(max_length=12)),
                ('balance', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
