# Generated by Django 3.2.15 on 2022-09-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_alter_account_contectno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='manno',
            new_name='panno',
        ),
    ]
