# Generated by Django 3.2.15 on 2022-09-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_rename_manno_account_panno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='emailaddress',
            new_name='emails',
        ),
    ]
